In [9]:
# The Purpose of this file is to learn to convert PDF files to workable data.
import pandas as pd

In [37]:
# Method1: pdfplumber -> extract text from PDF files.
import string

import pdfplumber
# Extract PDF data
text = ""
path = "Business Observations - Sheet8.pdf"
with pdfplumber.open(path) as pdf:
   for page in pdf.pages:
      text += page.extract_text()

strings = text.split("\n")

i = 0
n = 0
while i < len(strings):
    strings[i] = strings[i].split()
    for n in range(len(strings[i])):
      if strings[i][n] == "cartons":
         strings[i][n] = 0
      if i > 0:
         strings[i][n] = float(strings[i][n])
      n += 1
    i += 1
df = pd.DataFrame(strings).fillna(0)

df.columns = df.iloc[0]
df = df.drop(0)
df = df.reset_index(drop=True)


df.columns

Index(['05/03', '05/04', '05/10', '05/10', '05/11', '05/16', '05/16', '06/18',
       '05/19', '05/23', '05/23', '05/24', '05/30', '05/31', '06/01', '06/06',
       '06/07', '6/14', '06/14', '06/20'],
      dtype='object', name=0)

## Review of Method1:
    > * 'Unnamed' & 'NaN' don't have placeholders.
    > * Because, no placeholders, SHIFTING OF DATA FIELDS.
#### Thoughts:
    > * Great way to work with paragraph entries.
    > * Not great at working with data or tables.

In [ ]:
# Method2: tabula-py -> extract tables from PDF files.
import tabula

dfs = tabula.read_pdf("/workspaces/Interest/Business Observations - Sheet8.pdf", pages="all")
dfs[0].fillna(0)

,Unnamed: 0,05/03,05/04,Unnamed: 1,05/10,05/10.1,05/11,05/16,05/16.1,06/18,...,05/23.1,05/24,05/30,05/31,06/01,06/06,06/07,6/14,06/14,06/20
0,1,0.0,0.0,0.0,0.0,0.0,29.0,12.0,10.0,8.0,...,28.0,28.0,15.0,13.0,13,3.0,0.0,22.0,0.0,283
1,2,20.0,20.0,0.0,10.0,10.0,9.0,0.0,24.0,20.0,...,13.0,10.0,11.0,3.0,3,28.0,26.0,11.0,0.0,300
2,3,15.0,15.0,0.0,9.0,9.0,8.0,5.0,4.0,0.0,...,24.0,24.0,3.0,10.0,9,5.0,0.0,19.0,0.0,191
3,4,28.0,28.0,0.0,22.0,22.0,22.0,16.0,16.0,15.0,...,9.0,9.0,28.0,26.0,26,16.0,18.0,10.0,0.0,237
4,5,6.0,6.0,0.0,0.0,0.0,29.0,27.0,26.0,25.0,...,27.0,28.0,24.0,22.0,22,19.0,18.0,9.0,0.0,279
5,6,18.0,18.0,0.0,3.0,2.0,2.0,27.0,22.0,22.0,...,9.0,9.0,0.0,27.0,27,19.0,19.0,11.0,0.0,328
6,7,0.0,29.0,0.0,27.0,27.0,27.0,25.0,25.0,25.0,...,20.0,18.0,15.0,14.0,14,13.0,14.0,6.0,0.0,209
7,8,10.0,8.0,0.0,13.0,11.0,6.0,26.0,26.0,23.0,...,17.0,16.0,5.0,12.0,12,10.0,12.0,3.0,0.0,243
8,9,6.0,6.0,0.0,1.0,1.0,1.0,26.0,25.0,25.0,...,23.0,23.0,0.0,18.0,18,7.0,8.0,2.0,0.0,202
9,10,5.0,5.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0,...,27.0,27.0,0.0,21.0,21,12.0,14.0,6.0,0.0,97
10,11,17.0,17.0,0.0,10.0,10.0,10.0,9.0,9.0,9.0,...,0.0,27.0,0.0,13.0,29,12.0,31.0,19.0,0.0,43
11,12,0.0,27.0,0.0,1.0,1.0,0.0,14.0,1.0,0.0,...,0.0,28.0,0.0,0.0,0,28.0,4.0,14.0,0.0,88 cartons
12,13,12.0,5.0,0.0,21.0,21.0,28.0,8.0,5.0,27.0,...,2.0,2.0,0.0,11.0,27,27.0,0.0,0.0,0.0,0
13,14,0.0,29.0,0.0,19.0,18.0,15.0,8.0,6.0,29.0,...,16.0,16.0,0.0,4.0,2,10.0,17.0,4.0,0.0,0
14,15,16.0,0.0,0.0,13.0,4.0,1.0,8.0,2.0,0.0,...,12.0,6.0,0.0,17.0,16,21.0,0.0,0.0,0.0,0
15,16,14.0,18.0,0.0,0.0,0.0,28.0,12.0,0.0,0.0,...,3.0,2.0,0.0,0.0,29,54.0,16.0,16.0,0.0,0
16,17,14.0,14.0,0.0,59.0,59.0,59.0,26.0,23.0,14.0,...,50.0,43.0,0.0,7.0,4,10.0,48.0,24.0,0.0,0
17,18,5.0,0.0,0.0,7.0,5.0,28.0,3.0,0.0,28.0,...,26.0,26.0,0.0,24.0,23,9.0,8.0,1.0,0.0,0
18,19,8.0,8.0,0.0,0.0,0.0,29.0,22.0,20.0,14.0,...,8.0,8.0,0.0,17.0,15,10.0,13.0,2.0,0.0,0
19,20,7.0,6.0,0.0,0.0,0.0,0.0,55.0,50.0,50.0,...,45.0,44.0,0.0,6.0,4,47.0,5.0,28.0,0.0,0
20,21,27.0,22.0,0.0,0.0,0.0,59.0,36.0,22.0,17.0,...,44.0,42.0,0.0,15.0,12,28.0,39.0,11.0,0.0,0
21,22,40.0,39.0,0.0,11.0,8.0,5.0,6.0,0.0,23.0,...,4.0,0.0,0.0,30.0,29,17.0,28.0,38.0,0.0,0
22,23,16.0,16.0,0.0,46.0,46.0,31.0,49.0,43.0,32.0,...,1.0,0.0,0.0,35.0,34,55.0,7.0,6.0,0.0,0
23,24,0.0,0.0,0.0,47.0,47.0,46.0,32.0,27.0,27.0,...,17.0,15.0,0.0,57.0,56,36.0,50.0,43.0,0.0,0
24,25,0.0,0.0,0.0,0.0,0.0,48.0,0.0,47.0,45.0,...,57.0,57.0,0.0,40.0,33,0.0,6.0,37.0,0.0,0
25,26,17.0,31.0,0.0,7.0,1.0,1.0,40.0,39.0,37.0,...,22.0,21.0,0.0,2.0,2,7.0,55.0,47.0,0.0,0
26,27,27.0,15.0,0.0,0.0,0.0,57.0,45.0,39.0,31.0,...,11.0,9.0,0.0,24.0,22,14.0,59.0,39.0,0.0,0
27,28,31.0,31.0,0.0,27.0,27.0,27.0,24.0,23.0,23.0,...,20.0,20.0,0.0,16.0,16,84.0,11.0,62.0,0.0,0
28,29,0.0,56.0,0.0,41.0,41.0,40.0,20.0,16.0,13.0,...,59.0,57.0,0.0,90.0,90,63.0,0.0,8.0,0.0,0
29,30,46.0,46.0,0.0,32.0,32.0,32.0,22.0,18.0,18.0,...,0.0,97.0,0.0,75.0,75,69.0,0.0,50.0,0.0,0
30,31,42.0,34.0,0.0,1.0,1.0,148.0,45.0,45.0,44.0,...,120.0,118.0,0.0,101.0,101,116.0,0.0,31.0,0.0,0
31,32,80.0,80.0,0.0,72.0,71.0,148.0,70.0,68.0,67.0,...,19.0,19.0,0.0,130.0,129,99.0,0.0,68.0,0.0,0
32,33,0.0,0.0,0.0,121.0,117.0,116.0,34.0,33.0,33.0,...,142.0,138.0,0.0,122.0,122,104.0,0.0,76.0,0.0,0
33,34,82.0,82.0,0.0,64.0,64.0,63.0,33.0,33.0,33.0,...,133.0,125.0,0.0,110.0,110,107.0,0.0,78.0,0.0,0
34,35,3.0,75.0,0.0,58.0,58.0,48.0,133.0,178.0,128.0,...,146.0,146.0,0.0,110.0,107,280.0,0.0,55.0,0.0,0
35,36,69.0,66.0,0.0,24.0,21.0,20.0,0.0,273.0,264.0,...,114.0,116.0,0.0,72.0,71,0.0,0.0,169.0,0.0,0

## Method2: tabula 
> *Perfect Data Integrity
> *The file is converted directly into a DataFrame*
> *I am worried this method will not work in more complex files.*

In [3]:
# Method3: Camelot -> extract tables from PDF files.
import camelot

tables = camelot.read_pdf("/workspaces/Interest/Business Observations - Sheet8.pdf")
tables[0].df

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,,05/03,05/04,,05/10,05/10,05/11,05/16,05/16,06/18,...,05/23,05/24,05/30,05/31,06/01,06/06,06/07,6/14,06/14,06/20
1,1,0,0,,,,29,12,10,8,...,28,28,15,13,13,3,,22,,283
2,2,20,20,,10,10,9,,24,20,...,13,10,11,3,3,28,26,11,,300
3,3,15,15,,9,9,8,5,4,,...,24,24,3,10,9,5,,19,,191
4,4,28,28,,22,22,22,16,16,15,...,9,9,28,26,26,16,18,10,,237
5,5,6,6,,,,29,27,26,25,...,27,28,24,22,22,19,18,9,,279
6,6,18,18,,3,2,2,27,22,22,...,9,9,,27,27,19,19,11,,328
7,7,,29,,27,27,27,25,25,25,...,20,18,15,14,14,13,14,6,,209
8,8,10,8,,13,11,6,26,26,23,...,17,16,5,12,12,10,12,3,,243
9,9,6,6,,1,1,1,26,25,25,...,23,23,,18,18,7,8,2,,202
10,10,5,5,,4,4,4,0,0,,...,27,27,,21,21,12,14,6,,97
11,11,17,17,,10,10,10,9,9,9,...,,27,,13,29,12,31,19,,43
12,12,,27,,1,1,,14,1,,...,,28,,0,0,28,4,14,,88 cartons
13,13,12,5,,21,21,28,8,5,27,...,2,2,,11,27,27,,,,
14,14,,29,,19,18,15,8,6,29,...,16,16,,4,2,10,17,4,,
15,15,16,0,,13,4,1,8,2,,...,12,6,,17,16,21,,,,
16,16,14,18,,,,28,12,0,,...,3,2,,,29,54,16,16,,
17,17,14,14,,59,59,59,26,23,14,...,50,43,,7,4,10,48,24,,
18,18,5,,,7,5,28,3,,28,...,26,26,,24,23,9,8,1,,
19,19,8,8,,,,29,22,20,14,...,8,8,,17,15,10,13,2,,
20,20,7,6,,0,0,0,55,50,50,...,45,44,,6,4,47,5,28,,
21,21,27,22,,,,59,36,22,17,...,44,42,,15,12,28,39,11,,
22,22,40,39,,11,8,5,6,,23,...,4,,,30,29,17,28,38,,
23,23,16,16,,46,46,31,49,43,32,...,1,,,35,34,55,7,6,,
24,24,,,,47,47,46,32,27,27,...,17,15,,57,56,36,50,43,,
25,25,,,,,,48,0,47,45,...,57,57,,40,33,0,6,37,,
26,26,17,31,,7,1,1,40,39,37,...,22,21,,2,2,7,55,47,,
27,27,27,15,,,,57,45,39,31,...,11,9,,24,22,14,59,39,,
28,28,31,31,,27,27,27,24,23,23,...,20,20,,16,16,84,11,62,,
29,29,,56,,41,41,40,20,16,13,...,59,57,,90,90,63,,8,,
30,30,46,46,,32,32,32,22,18,18,...,,97,,75,75,69,,50,,
31,31,42,34,,1,1,148,45,45,44,...,120,118,,101,101,116,,31,,
32,32,80,80,,72,71,148,70,68,67,...,19,19,,130,129,99,,68,,
33,33,,,,121,117,116,34,33,33,...,142,138,,122,122,104,,76,,
34,34,82,82,,64,64,63,33,33,33,...,133,125,,110,110,107,,78,,
35,35,3,75,,58,58,48,133,178,128,...,146,146,,110,107,280,,55,,
36,36,69,66,,24,21,20,,273,264,...,114,116,,72,71,,,169,,

## Method3: Winner for data integrity
> *Combined Data Integrity and Ease-of-Use
> *Will be my first choice when working with PDF formatted tables.

In [ ]:
# ==========================
# **
# If the PDF is scanned or image
# **
# You'll need OCR (Optical Character Recognition).
# **
# 1) pdf2image -> convert PDF pages to images.
# 2) pytesseract -> extract text from images.
# ***
# ===========================

In [5]:
# Method4: pdf2image + pytesseract -> extract text from scanned PDF files.
from pdf2image import convert_from_path
import pytesseract

pages = convert_from_path("Business Observations - Sheet8.pdf")

text = ""
for page in pages:
   text += pytesseract.image_to_string(page)

print(text)

PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?